apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opsera-february-greeting-app-dev
  namespace: argocd
  labels:
    app: february-greeting-app
    tenant: opsera
    environment: dev
    managed-by: opsera-c2c
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/PrabakarNallamuthu/february-greeting-app.git
    targetRevision: main
    path: .opsera-february-greeting-app/k8s/overlays/dev
  destination:
    name: opsera-usw2-np
    namespace: opsera-february-greeting-app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
