apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-february-greeting-app-dev

resources:
  - ../../base

images:
  - name: all-is-well
    newName: PLACEHOLDER_ECR_URI
    newTag: latest

patches:
  - target:
      kind: Ingress
      name: february-greeting-app
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: february-greeting-app-dev.agent.opsera.dev

labels:
  - includeSelectors: false
    pairs:
      environment: dev
