apiVersion: v1
kind: Service
metadata:
  name: february-greeting-app
  labels:
    app: february-greeting-app
    tenant: opsera
    managed-by: opsera-c2c
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: february-greeting-app
